### ISSUE TITLE
"key" parameter is missing

### ISSUE THREAD

**Issue by fregante** [relative-ci/agent-action#442]
I've had this config for a long time, the secret has been there unchanged for 4 years.

```yml
      - name: Send build stats to RelativeCI
        if: matrix.os == 'ubuntu-latest'
        uses: relative-ci/agent-action@v2
        with:
          token: ${{ github.token }}
          webpackStatsFile: ./distribution/assets/webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
```

Today I'm seeing this issue on a long-time collaborator's PR (cross-repo)

```
Error: Error: "key" parameter is missing, make sure to set RELATIVE_CI_KEY environment variable! Read more about RelativeCI agent setup at https://relative-ci.com/documentation/setup.
```

Was anything changed in the latest release?

It works in a local PR:

- https://github.com/refined-github/refined-github/actions/runs/13849656687/job/38754654420?pr=8335

But not here:

- https://github.com/refined-github/refined-github/actions/runs/13849453450/job/38754475603?pr=8334

See full workflow here:

- https://github.com/refined-github/refined-github/actions/runs/13849453450/workflow?pr=8334#L105
